# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_auto_20171019_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatedobject',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'Pending'), (3, 'View Able Pending')], default=2, editable=False),
        ),
    ]
