# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0005_auto_20171007_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planattributecategory',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Attribute category', 'verbose_name_plural': 'Attribute categories'},
        ),

        migrations.AddField(
            model_name='planannualattribute',
            name='is_from_source',
            field=models.BooleanField(default=True),
        ),

        migrations.AddField(
            model_name='planattribute',
            name='attributes_for_master',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Attributes for Master'),
        ),
    ]
