# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0006_auto_20171115_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planannualattribute',
            name='is_from_source',
            field=models.BooleanField(default=True, help_text='check if the value is from source or from user just for Master Attribute'),
        ),
        migrations.AlterField(
            model_name='planattribute',
            name='attributes_for_master',
            field=models.CharField(blank=True, help_text='Source Attributes for the master attribute', max_length=256, null=True, verbose_name='Source Attributes'),
        ),
    ]
