# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0010_auto_20171117_0903'),
    ]

    operations = [

        migrations.AlterField(
            model_name='plan',
            name='census_plan_id',
            field=models.CharField(max_length=255, unique=True),
        ),


    ]
