# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0013_auto_20171125_0334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanAttributeCategory',
            new_name='AttributeCategory',
        ),
    ]
