# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0020_governmentattrsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CensusData',
        ),
    ]
