# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0021_delete_censusdata'),
    ]

    operations = [

        migrations.RenameField(
            model_name='governmentannualattribute',
            old_name='value',
            new_name='attribute_value',
        ),

        migrations.AlterField(
            model_name='governmentannualattribute',
            name='attribute_value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
