# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAnnualAttribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('attribute_value', models.TextField()),
            ],
            options={
                'db_table': 'plan_annual_attribute',
                'managed': False,
            },
        ),
    ]
