# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0003_auto_20170922_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='censusdata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='datasource',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='governmentannual',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='governmentattribute',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='governmenttype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='planannual',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='planannualattribute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='planinheritance',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='planprovisions',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='planattribute',
            name='attribute_type',
            field=models.CharField(choices=[('static', 'static'), ('calculated', 'calculated')], default='static', max_length=16),
        ),
        migrations.AddField(
            model_name='planattribute',
            name='calculated_rule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planattribute',
            name='datatype',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='planattribute',
            name='line_item_code',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='planattributemaster',
            name='plan_attribute_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pensiondata.PlanAttributeCategory'),
        ),
        migrations.AlterModelTable(
            name='censusannualattribute',
            table='census_annual_attribute_mv',
        ),
    ]
