# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0007_auto_20171117_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='planattribute',
            name='weight',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
