# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0009_weight_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planannualattribute',
            name='is_from_source',
            field=models.NullBooleanField(default=None,
                                          help_text='check if the value is from source or from user just for Master Attribute'),
        ),
    ]
