# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0012_auto_20171125_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planattribute',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=6, default=1000, max_digits=30, null=True),
        ),

        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='planattribute',
            unique_together=set([('data_source', 'line_item_code')]),
        ),
    ]
