# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0014_auto_20171126_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentattribute',
            name='government_attribute_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='pensiondata.AttributeCategory'),
        ),
    ]
