# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0015_auto_20171126_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributecategory',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Attribute Category',
                     'verbose_name_plural': 'Attribute Categories'},
        ),

        migrations.RenameField(
            model_name='planattribute',
            old_name='plan_attribute_category',
            new_name='attribute_category',
        ),

        migrations.RenameField(
            model_name='governmentattribute',
            old_name='government_attribute_category',
            new_name='attribute_category',
        ),

        migrations.AlterModelTable(
            name='attributecategory',
            table='attribute_category',
        ),
    ]
