# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0016_auto_20171126_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentAnnualAttribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Government Annual Attribute',
                'verbose_name_plural': 'Government Annual Attributes',
                'db_table': 'government_annual_attribute',
            },
        ),
        migrations.DeleteModel(
            name='GovernmentAnnual',
        ),
        migrations.RemoveField(
            model_name='planattributemaster',
            name='plan_attribute_category',
        ),

        migrations.RemoveField(
            model_name='county',
            name='county_fips_code',
        ),
        migrations.RemoveField(
            model_name='county',
            name='fips_class_code',
        ),
        migrations.RemoveField(
            model_name='county',
            name='state_fips_code',
        ),
        migrations.RemoveField(
            model_name='state',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='state',
            name='state_fips_code',
        ),
        migrations.AddField(
            model_name='county',
            name='retirement_census_county_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='retirement_census_state_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pensiondata.State'),
        ),
        migrations.AddField(
            model_name='government',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pensiondata.County'),
        ),
        migrations.AddField(
            model_name='government',
            name='government_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pensiondata.GovernmentType'),
        ),
        migrations.AddField(
            model_name='government',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pensiondata.State'),
        ),
        migrations.AddField(
            model_name='governmentattribute',
            name='attribute_column_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),

        migrations.AddField(
            model_name='governmentattribute',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pensiondata.DataSource'),
        ),
        migrations.AddField(
            model_name='governmentattribute',
            name='datatype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='governmentattribute',
            name='display_order',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='governmentattribute',
            name='line_item_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='governmentattribute',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='governmentattribute',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='governmentattribute',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='planannual',
            name='government_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planannual',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pensiondata.Plan'),
        ),
        migrations.AddField(
            model_name='state',
            name='retirement_census_state_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='state_abbreviation',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),

        migrations.RemoveField(
            model_name='governmentattribute',
            name='attribute_datatype',
        ),
        migrations.RemoveField(
            model_name='governmentattribute',
            name='attribute_key',
        ),

        migrations.DeleteModel(
            name='PlanAttributeMaster',
        ),

        migrations.AddField(
            model_name='governmentannualattribute',
            name='government',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pensiondata.Government'),
        ),

        migrations.AddField(
            model_name='governmentannualattribute',
            name='government_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='annual_attrs', to='pensiondata.GovernmentAttribute'),
        ),
    ]
