# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0017_auto_20171126_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='government',
            options={'verbose_name': 'Government', 'verbose_name_plural': 'Governments'},
        ),
        migrations.AlterModelOptions(
            name='governmentattribute',
            options={'managed': True, 'verbose_name': 'Government Attribute',
                     'verbose_name_plural': 'Government Attributes'},
        ),
        migrations.AlterModelOptions(
            name='governmenttype',
            options={'managed': True, 'verbose_name': 'Government Type', 'verbose_name_plural': 'Government Types'},
        ),
        migrations.AlterModelOptions(
            name='planannualattribute',
            options={'verbose_name': 'Plan Annual Attribute', 'verbose_name_plural': 'Plan Annual Attributes'},
        ),
        migrations.AlterModelOptions(
            name='planattribute',
            options={'managed': True, 'verbose_name': 'Plan Attribute', 'verbose_name_plural': 'Plan Attributes'},
        ),
        migrations.AddField(
            model_name='governmentannualattribute',
            name='is_from_source',
            field=models.NullBooleanField(default=None,
                                          help_text='check if the value is from source or from user just for Master Attribute'),
        ),
        migrations.AddField(
            model_name='governmentattribute',
            name='attribute_type',
            field=models.CharField(choices=[('static', 'static'), ('calculated', 'calculated')], default='static',
                                   max_length=16),
        ),
        migrations.AddField(
            model_name='governmentattribute',
            name='attributes_for_master',
            field=models.CharField(blank=True, help_text='Source Attributes for the master attribute', max_length=256,
                                   null=True, verbose_name='Source Attributes'),
        ),
        migrations.AddField(
            model_name='governmentattribute',
            name='calculated_rule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='governmentattribute',
            name='datatype',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='governmentattribute',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='governmentattribute',
            name='line_item_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='governmentattribute',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=6, default=1000, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='governmentattribute',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='governmentattribute',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='governmentannualattribute',
            unique_together=set([('government', 'year', 'government_attribute')]),
        ),
        migrations.AlterUniqueTogether(
            name='governmentattribute',
            unique_together=set([('data_source', 'line_item_code')]),
        ),
    ]
