# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0018_auto_20171126_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'managed': True, 'ordering': ('trust_level',), 'verbose_name': 'Data Source', 'verbose_name_plural': 'Data Sources'},
        ),
    ]
