# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0019_auto_20171127_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentAttrSummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('datatype', models.CharField(blank=True, max_length=256, null=True)),
                ('line_item_code', models.CharField(blank=True, max_length=256, null=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('attribute_column_name', models.CharField(blank=True, max_length=256, null=True)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=6, default=1000, max_digits=30, null=True)),
                ('weight', models.IntegerField(default=0)),
                ('attributes_for_master', models.CharField(blank=True, help_text='Source Attributes for the master attribute', max_length=256, null=True, verbose_name='Source Attributes')),
                ('attribute_type', models.CharField(choices=[('static', 'static'), ('calculated', 'calculated')], default='static', max_length=16)),
                ('calculated_rule', models.TextField(blank=True, null=True)),
                ('data_source_id', models.IntegerField()),
                ('attribute_category_id', models.IntegerField()),
                ('data_source_name', models.CharField(max_length=255)),
                ('attribute_category_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'governmentattrview',
                'managed': False,
            },
        ),
    ]
