# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0023_auto_20171127_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentattribute',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=6, default=1000, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='governmentattribute',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
