# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0024_auto_20171128_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentattribute',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planattribute',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
