# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0025_auto_20171128_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Presentation Export', max_length=100)),
                ('export_type', models.CharField(choices=[('xlsx', 'xlsx')], default='xlsx', max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationExport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('export_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pensiondata.ExportGroup')),
                ('government_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pensiondata.GovernmentAttribute')),
                ('plan_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pensiondata.PlanAttribute')),
            ],
            options={
                'db_table': 'presentation_export',
            },
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='planannualattribute',
            options={'verbose_name': 'Plan Annual Attribute', 'verbose_name_plural': 'Import Plan Annual Attributes'},
        ),
        migrations.AlterUniqueTogether(
            name='presentationexport',
            unique_together=set([('export_group', 'government_field'), ('export_group', 'plan_field')]),
        ),
    ]
