# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0027_auto_20180205_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateCalculatedAttributeData',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Generate Calculated Attribute Data',
                'proxy': True,
                'indexes': [],
            },
            bases=('pensiondata.planattribute',),
        ),
        migrations.AlterField(
            model_name='governmentattribute',
            name='datatype',
            field=models.CharField(blank=True, choices=[('int', 'int'), ('int_separated3', 'int_separated3'), ('percentage', 'percentage'), ('percentage2', 'percentage2'), ('percentage4', 'percentage4'), ('real', 'real'), ('text', 'text'), ('yesno', 'yesno')], max_length=256, null=True),
        ),
    ]
