# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0031_planattribute_status_calculated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanBenefitDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.FloatField(blank=True, null=True)),
                ('slepp_record_id', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('tier', models.CharField(blank=True, max_length=255, null=True)),
                ('hired_before_date', models.DateTimeField(blank=True, null=True)),
                ('hired_on_or_after_date', models.DateTimeField(blank=True, null=True)),
                ('covers_new_hires', models.FloatField(blank=True, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_contribution_rate', models.FloatField(blank=True, null=True)),
                ('vesting_years', models.FloatField(blank=True, null=True)),
                ('retirement_eligibility_normal', models.CharField(blank=True, max_length=255, null=True)),
                ('retirement_eligibility_early', models.CharField(blank=True, max_length=255, null=True)),
                ('formula_benefit', models.CharField(blank=True, max_length=255, null=True)),
                ('final_average_salary', models.CharField(blank=True, max_length=255, null=True)),
                ('multiplier', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_supplement', models.TextField(blank=True, null=True)),
                ('penalty_for_early_retirement', models.CharField(blank=True, max_length=255, null=True)),
                ('early_retirement_formula', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_details_on_early_retirement_penalties', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_of_living_adjustment', models.CharField(blank=True, max_length=255, null=True)),
                ('deferred_vested_start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('increases_in_deferred_vested_benefits', models.CharField(blank=True, max_length=255, null=True)),
                ('mandatory_retirement', models.CharField(blank=True, max_length=255, null=True)),
                ('deferred_retirement_option_program', models.FloatField(blank=True, null=True)),
                ('vesting_in_years_non_fas_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_contribution_rate_non_fas_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_contribution_ratenon_fas_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_rate_non_fas_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('social_security_coverage', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan_benefit_design',
                'managed': False,
            },
        ),
    ]
