# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0032_planbenefitdesign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planbenefitdesign',
            options={},
        ),
    ]
