# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0033_auto_20180308_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planbenefitdesign',
            name='plan_id',
        ),
        migrations.AddField(
            model_name='planbenefitdesign',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planbenefitdesign',
            name='plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pensiondata.Plan'),
        ),
    ]
