# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0035_auto_20180308_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='system_assigned_employer_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='System Assigned Employer ID'),
        ),
    ]
