# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0036_plan_system_assigned_employer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
