# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-15 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0038_auto_20180314_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
