# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-15 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0040_auto_20180315_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='employ_gov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employ_gov', to='pensiondata.Government', verbose_name='Employing Gov'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='admin_gov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_gov', to='pensiondata.Government'),
        ),
    ]
