# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-16 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pensiondata.models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0042_auto_20180316_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('census_plan_id', pensiondata.models.CharNullField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_inception', models.IntegerField(blank=True, null=True)),
                ('benefit_tier', models.IntegerField(blank=True, null=True)),
                ('year_closed', models.IntegerField(blank=True, null=True)),
                ('web_site', models.CharField(blank=True, max_length=255, null=True)),
                ('soc_sec_coverage', models.NullBooleanField()),
                ('soc_sec_coverage_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('includes_state_employees', models.NullBooleanField()),
                ('includes_local_employees', models.NullBooleanField()),
                ('includes_safety_employees', models.NullBooleanField()),
                ('includes_general_employees', models.NullBooleanField()),
                ('includes_teachers', models.NullBooleanField()),
                ('intra_period_data_entity_id', models.BigIntegerField(blank=True, null=True)),
                ('intra_period_data_period_end_date', models.DateField(blank=True, null=True)),
                ('intra_period_data_period_type', models.IntegerField(blank=True, null=True)),
                ('gasb_68_type', models.CharField(blank=True, max_length=30, null=True)),
                ('state_gov_role', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('system_assigned_employer_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='System Assigned Employer ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('year', models.CharField(max_length=4)),
                ('admin_gov', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_gov_report', to='pensiondata.Government')),
                ('employ_gov', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employ_gov_report', to='pensiondata.Government', verbose_name='Employing Gov')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pensiondata.Plan')),
            ],
            options={
                'db_table': 'reporting_table',
            },
        ),
    ]
