# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-16 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0043_reportingtable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportingtable',
            table=None,
        ),
    ]
