# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-01 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0045_auto_20190330_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planannualmasterattribute',
            options={'verbose_name': 'Plan Annual Master Attribute', 'verbose_name_plural': 'Plan Annual Master Attributes'},
        ),
        migrations.RemoveField(
            model_name='planattributemaster',
            name='data_source',
        ),
    ]
