# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-01 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0046_auto_20190401_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planannualmasterattribute',
            name='is_from_source',
        ),
        migrations.AlterField(
            model_name='planannualmasterattribute',
            name='plan_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='annual_master_attrs', to='pensiondata.PlanMasterAttributeNames'),
        ),
    ]
