# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-19 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0050_sproc_master_attribute'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planannualmasterattribute',
            unique_together=set([('plan', 'year', 'plan_attribute', 'master_attribute')]),
        ),
    ]
