# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0052_sproc_master_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapCharts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('stored_procedure', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Map Charts',
                'db_table': 'map_charts',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='planattributemaster',
            options={'managed': True, 'verbose_name': 'Plan Attribute to Master Mapping'},
        ),
    ]
