# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-05 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiondata', '0053_auto_20190828_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcharts',
            name='header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mapcharts',
            name='y_axis_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mapcharts',
            name='stored_procedure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mapcharts',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
